Replace u_intXX_t with kernel typedefs
u_intXX_t requires including sys/types.h which might not work in kernel
code, if this header is used in a kernel module

Fixes
| In file included from ufs.c:16:
| In file included from ./ufs.h:9:
| ./scsi_bsg_util.h:131:2: error: unknown type name 'u_int16_t'; did you mean 'uint16_t'?
|         u_int16_t result;
|         ^~~~~~~~~

Signed-off-by: Khem Raj <raj.khem@gmail.com>